AWSTemplateFormatVersion: '2010-09-09'
Description: 'ec2_auto_shutdown

  SAM Template for ec2_auto_shutdown

  '
Globals:
  Function:
    Timeout: 3
Outputs:
  EC2AutoStopFunction:
    Description: EC2AutoStopFunction ARN
    Value:
      Fn::GetAtt:
      - EC2AutoStopFunction
      - Arn
Resources:
  EC2AutoStopFunction:
    Properties:
      AutoPublishAlias: v1
      CodeUri: s3://aws.wi.fork.co.jp/34bcdb98158d350e54bed9e5341e24fa
      Events:
        Timer:
          Properties:
            Schedule: cron(15 12 * * ? *)
          Type: Schedule
      FunctionName: EC2AutoStopFunction
      Handler: lambda_function.lambda_handler
      Policies:
      - Statement:
        - Action:
          - ec2:Describe*
          - ec2:StopInstances
          Effect: Allow
          Resource: '*'
          Sid: ''
        Version: '2012-10-17'
      Runtime: python3.7
      Tags:
        runtype: prod
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
